#!/bin/bash

make="${MAKE:-make}"

makesample=true
if [[ $1 == "--nosample" ]]
then
	makesample=false
	shift
fi

cd lib
$make $1 $2 || exit

cd usb
$make $1 $2 || exit
cd ..

cd input
$make $1 $2 || exit
cd ..

cd fs
$make $1 $2 || exit

cd fat
$make $1 $2 || exit
cd ../..

cd sched
$make $1 $2 || exit
cd ..

cd net
$make $1 $2 || exit
cd ..

cd bt
$make $1 $2 || exit
cd ../..

cd addon/linux
$make $1 $2 || exit
cd ..

cd SDCard
$make $1 $2 || exit
cd ../..

cd addon/vc4
source ./makeall $1 $2 || exit
cd interface
source ./makeall $1 $2 || exit
cd ../../..

if [[ $makesample == true ]]
then
	cd sample
	./makelatest $1 $2 || exit
	cd ..
fi
